table 'Backlog BUR'
	lineageTag: 7bfd919c-0ade-4274-b214-f6313275d51c

	column FILIAL
		dataType: int64
		formatString: 0
		lineageTag: 9e30ada1-abe1-4e07-9ff5-8d6be3358e34
		summarizeBy: sum
		sourceColumn: FILIAL

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'ORD SERV'
		dataType: int64
		formatString: 0
		lineageTag: 7254ff05-8c14-41c5-8c45-49eaab7d5f3d
		summarizeBy: sum
		sourceColumn: ORD SERV

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column CLIENTE
		dataType: string
		lineageTag: 7a373a43-689b-4564-a638-f67b3740559f
		summarizeBy: none
		sourceColumn: CLIENTE

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'FIS JUR'
		dataType: string
		lineageTag: ee08773b-ebe2-4908-848e-5ea92cc054b9
		summarizeBy: none
		sourceColumn: FIS JUR

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column CGC
		dataType: int64
		formatString: 0
		lineageTag: bc07b792-4d8f-4bd4-9459-05663846128c
		summarizeBy: sum
		sourceColumn: CGC

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column STATUS
		dataType: int64
		formatString: 0
		lineageTag: 30de5b7f-b946-4532-b64e-d66b15b8393a
		summarizeBy: sum
		sourceColumn: STATUS

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'DT ENTRADA'
		dataType: dateTime
		formatString: General Date
		lineageTag: da6c237c-8034-43bd-829b-4c27c4724882
		summarizeBy: none
		sourceColumn: DT ENTRADA

		variation Variation
			isDefault
			relationship: 7807c776-ee64-48a4-87c6-74bc62bf6efd
			defaultHierarchy: LocalDateTable_cfa92260-6238-44ee-92e6-608c77aa8ad2.'Hierarquia de datas'

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'VL ADIANTAMENTO'
		dataType: int64
		formatString: 0
		lineageTag: b683d495-2a57-4a17-adfd-ed596e6285b1
		summarizeBy: sum
		sourceColumn: VL ADIANTAMENTO

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column REFERENCIA
		dataType: string
		lineageTag: 24034e9d-8478-4f5c-bf18-bcd4e9b4252e
		summarizeBy: none
		sourceColumn: REFERENCIA

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column SERIE
		dataType: string
		lineageTag: 8ee0abbe-109d-4aae-9d6d-c87b01f127e8
		summarizeBy: none
		sourceColumn: SERIE

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column SEGMENTACAO
		dataType: string
		lineageTag: e730c3c6-c0f2-413e-aa52-44e488a40972
		summarizeBy: none
		sourceColumn: SEGMENTACAO

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column MARCA
		dataType: string
		lineageTag: 194f17fd-3dfd-409d-84c8-6c312d2402a0
		summarizeBy: none
		sourceColumn: MARCA

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'TIPO CLIENTE'
		dataType: string
		lineageTag: df1871c8-3070-4cf5-8285-5eeddcf4a0a5
		summarizeBy: none
		sourceColumn: TIPO CLIENTE

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'VL SERVICO'
		dataType: double
		lineageTag: 19777130-c63e-493b-963b-619f8727e6e4
		summarizeBy: sum
		sourceColumn: VL SERVICO

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'VL PECA'
		dataType: int64
		formatString: 0
		lineageTag: 207f2c67-5bf9-46c6-92c2-8498abc5241a
		summarizeBy: sum
		sourceColumn: VL PECA

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'VL ORCAMENTO'
		dataType: double
		lineageTag: 70521b97-7e27-4cda-96b9-ed9dab4c2934
		summarizeBy: sum
		sourceColumn: VL ORCAMENTO

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'DESC STATUS'
		dataType: string
		lineageTag: 699973c6-5f8f-4385-aa34-baa28efbe87c
		summarizeBy: none
		sourceColumn: DESC STATUS

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Numrelogiotrocado
		dataType: string
		lineageTag: e767772b-77e3-458c-bbd2-095a62f9816b
		summarizeBy: none
		sourceColumn: Numrelogiotrocado

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'DT ENT FIL'
		dataType: dateTime
		formatString: Short Date
		lineageTag: f8116047-77f9-4fd9-9ea6-0870cdad9bc9
		summarizeBy: none
		sourceColumn: DT ENT FIL

		variation Variation
			isDefault
			relationship: 15f4a259-c148-494d-baee-7c4a8ffaf46f
			defaultHierarchy: LocalDateTable_438a7434-3e56-4919-8c21-0648888c7399.'Hierarquia de datas'

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'FIL ORD SERV IMP'
		dataType: int64
		formatString: 0
		lineageTag: 1f228d5a-bc46-445b-acb9-49c985fc89ed
		summarizeBy: sum
		sourceColumn: FIL ORD SERV IMP

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'ORD SERV IMP'
		dataType: int64
		formatString: 0
		lineageTag: 3bd3b144-5711-4216-9af1-9c4e3afa8442
		summarizeBy: sum
		sourceColumn: ORD SERV IMP

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'DATA STATUS'
		dataType: dateTime
		formatString: General Date
		lineageTag: bb531240-557f-46d8-b209-1f73d3cb55a1
		summarizeBy: none
		sourceColumn: DATA STATUS

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'DT CONCLUSAO'
		dataType: dateTime
		formatString: General Date
		lineageTag: 04ee1cee-5362-4d79-84c3-6e380d7b0ef3
		summarizeBy: none
		sourceColumn: DT CONCLUSAO

		variation Variation
			isDefault
			relationship: ad7b11e5-a4be-473f-8896-dcecadbc3f4d
			defaultHierarchy: LocalDateTable_4144c67f-fee5-44d4-acfa-452abf58dbf3.'Hierarquia de datas'

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'DT ESTORNO'
		dataType: dateTime
		formatString: General Date
		lineageTag: 571e390c-4d72-4f0d-b43a-9179f8539870
		summarizeBy: none
		sourceColumn: DT ESTORNO

		variation Variation
			isDefault
			relationship: fb7e2702-cd08-4727-a6d9-2436fbab970a
			defaultHierarchy: LocalDateTable_b1a18618-9692-45bf-ad1e-c12974e9cebe.'Hierarquia de datas'

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'DT CONCLUIDO'
		dataType: string
		lineageTag: 838bf4d0-dcdd-44c3-aea0-b37c2147bbe4
		summarizeBy: none
		sourceColumn: DT CONCLUIDO

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Tipo =
			
			IF(
			    'Backlog BUR'[REFERENCIA] IN VALUES('Parametro Smarts'[REF_SMART]),
			    "SMART",
			    "Tradicional"
			)
		lineageTag: 31493d3e-5292-4e5a-9f0a-7aa632cb7a98
		summarizeBy: none

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Marca_Check = ```
			
			VAR Resultado_Parametro =
			    LOOKUPVALUE(
			        'Parametro Smarts'[Marca_SKU],
			        'Parametro Smarts'[REF_SMART],
			        'Backlog BUR'[REFERENCIA]
			    )
			
			VAR Resultado_OS =
			    LOOKUPVALUE(
			        'OS_Geral'[Marca],
			        'OS_Geral'[Referência],
			        'Backlog BUR'[REFERENCIA]
			    )
			
			VAR Resultado_BUR = 
			    'Backlog BUR'[MARCA]
			
			RETURN
			    COALESCE(
			        Resultado_Parametro,
			        Resultado_OS,
			        Resultado_BUR
			    )
			```
		lineageTag: 7b8d4edb-9a8c-4257-98c0-689b78f9559a
		summarizeBy: none

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	partition 'Backlog BUR' = m
		mode: import
		source =
				let
				    Fonte = Excel.Workbook(File.Contents("T:\Departamental\PÓS VENDA\Laboratorio\Fornitura\KPI\Dashboard AST\Dashboard Technos\Bases QUERY - AST\QUERY - Backlog BUR.xlsx"), null, true),
				    #"QUERY - Backlog BUR_Sheet" = Fonte{[Item="QUERY - Backlog BUR",Kind="Sheet"]}[Data],
				    #"Cabeçalhos Promovidos" = Table.PromoteHeaders(#"QUERY - Backlog BUR_Sheet", [PromoteAllScalars=true]),
				    #"Tipo Alterado" = Table.TransformColumnTypes(#"Cabeçalhos Promovidos",{{"AST_QUERY_BacklogBUR", type any}, {"Column2", type any}, {"Column3", type text}, {"Column4", type text}, {"Column5", type text}, {"Column6", type any}, {"Column7", type any}, {"Column8", type any}, {"Column9", type text}, {"Column10", type text}, {"Column11", type text}, {"Column12", type text}, {"Column13", type text}, {"Column14", type any}, {"Column15", type any}, {"Column16", type any}, {"Column17", type text}, {"Column18", type text}, {"Column19", type any}, {"Column20", type text}, {"Column21", type any}, {"Column22", type any}, {"Column23", type any}, {"Column24", type any}, {"Column25", type text}}),
				    #"Cabeçalhos Promovidos1" = Table.PromoteHeaders(#"Tipo Alterado", [PromoteAllScalars=true]),
				    #"Tipo Alterado1" = Table.TransformColumnTypes(#"Cabeçalhos Promovidos1",{{"FILIAL", Int64.Type}, {"ORD SERV", Int64.Type}, {"CLIENTE", type text}, {"FIS JUR", type text}, {"CGC", Int64.Type}, {"STATUS", Int64.Type}, {"DT ENTRADA", type datetime}, {"VL ADIANTAMENTO", Int64.Type}, {"REFERENCIA", type text}, {"SERIE", type text}, {"SEGMENTACAO", type text}, {"MARCA", type text}, {"TIPO CLIENTE", type text}, {"VL SERVICO", type number}, {"VL PECA", Int64.Type}, {"VL ORCAMENTO", type number}, {"DESC STATUS", type text}, {"Numrelogiotrocado", type text}, {"DT ENT FIL", type datetime}, {"FIL ORD SERV IMP", Int64.Type}, {"ORD SERV IMP", Int64.Type}, {"DATA STATUS", type datetime}, {"DT CONCLUSAO", type datetime}, {"DT ESTORNO", type datetime}, {"DT CONCLUIDO", type text}})
				in
				    #"Tipo Alterado1"

	changedProperty = IsHidden

	annotation PBI_NavigationStepName = Navegação

	annotation PBI_ResultType = Table

