table 'Parametro Smarts'
	lineageTag: 9a343c0e-8fd6-4c5b-b030-ffa50681aa38

	column REF_SMART
		dataType: string
		lineageTag: 4c2d56c1-6f2e-48a8-bd91-310e4b09db58
		summarizeBy: none
		sourceColumn: REF_SMART

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'TIPO SMART'
		dataType: string
		lineageTag: 2f1afcd0-3830-4a76-9af1-b42520303d4e
		summarizeBy: none
		sourceColumn: TIPO SMART

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column SMART?
		dataType: string
		lineageTag: 59979f28-cac3-4b81-a081-cb109cae07a7
		summarizeBy: none
		sourceColumn: SMART?

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Familia_SKU
		dataType: string
		lineageTag: 54da4f24-a538-4f43-a0fe-fd1fe3ffd1da
		summarizeBy: none
		sourceColumn: Familia_SKU

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Marca_SKU
		dataType: string
		lineageTag: 85714c75-03b5-4140-b15d-7a8cf6218ae9
		summarizeBy: none
		sourceColumn: Marca_SKU

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Raiz
		dataType: string
		lineageTag: 10c7a57f-9c1e-4d1f-8b98-3fcf814a929d
		summarizeBy: none
		sourceColumn: Raiz

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column REFERENCIA
		dataType: string
		lineageTag: 632c747b-cd06-4faf-975d-8567d2b2e72a
		summarizeBy: none
		sourceColumn: REFERENCIA

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column REF_SMART_1
		dataType: string
		lineageTag: b43a6abf-9894-4a4b-b9cf-d2f6e6e35382
		summarizeBy: none
		sourceColumn: REF_SMART_1

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'TIPO SMART_2'
		dataType: string
		lineageTag: 7a1fba53-4530-4045-95ec-dc6992d66bb0
		summarizeBy: none
		sourceColumn: TIPO SMART_2

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column SMART?_3
		dataType: string
		lineageTag: b6a6224b-96ac-440d-b019-d4cea965a109
		summarizeBy: none
		sourceColumn: SMART?_3

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Familia_SKU_4
		dataType: string
		lineageTag: 87112c92-052d-46f8-91cb-58311b1fa775
		summarizeBy: none
		sourceColumn: Familia_SKU_4

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Marca_SKU_5
		dataType: string
		lineageTag: f3c0e440-f21e-456a-8c65-315d4ea22b56
		summarizeBy: none
		sourceColumn: Marca_SKU_5

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Mês
		dataType: int64
		formatString: 0
		lineageTag: 2376064b-27bb-4821-a64d-4b7d1541506f
		summarizeBy: none
		sourceColumn: Mês

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Mês_6
		dataType: string
		lineageTag: 81022bea-5808-4cb3-bb64-2c3fbbe49e71
		summarizeBy: none
		sourceColumn: Mês_6

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Classificação
		dataType: string
		lineageTag: eec62874-d60d-4052-a2ff-eaaa50417e30
		summarizeBy: none
		sourceColumn: Classificação

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Column11
		dataType: string
		lineageTag: 1d8fd5f2-7bfd-4eed-a3c6-80facddbfc70
		summarizeBy: none
		sourceColumn: Column11

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Column18
		dataType: string
		lineageTag: 935c7176-7a1b-46ab-9666-6ba4d9105aa5
		summarizeBy: none
		sourceColumn: Column18

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Fornecedor
		dataType: string
		lineageTag: 5a789320-b1b2-40e2-acfb-1a07a0f3995c
		summarizeBy: none
		sourceColumn: Fornecedor

		annotation SummarizationSetBy = Automatic

	column Column8
		dataType: string
		lineageTag: 20f73b1d-238c-471e-b80e-37807232dedf
		summarizeBy: none
		sourceColumn: Column8

		annotation SummarizationSetBy = Automatic

	column Column12
		dataType: string
		lineageTag: 5c7889b8-097f-4181-b1fe-e4f7ec4cba97
		summarizeBy: none
		sourceColumn: Column12

		annotation SummarizationSetBy = Automatic

	column Column19
		dataType: string
		lineageTag: 7a1f252d-8643-4df0-856f-b4b0a909c4a2
		summarizeBy: none
		sourceColumn: Column19

		annotation SummarizationSetBy = Automatic

	partition 'Parametro Smarts' = m
		mode: import
		source =
				let
				    Fonte = Excel.Workbook(File.Contents("T:\Departamental\PÓS VENDA\Laboratorio\Fornitura\KPI\Dashboard AST\Dashboard Technos\Bases QUERY - AST\Parametro Smartwatch.xlsx"), null, true),
				    #"Parametro Smarts_Sheet" = Fonte{[Item="Parametro Smarts",Kind="Sheet"]}[Data],
				    #"Cabeçalhos Promovidos" = Table.PromoteHeaders(#"Parametro Smarts_Sheet", [PromoteAllScalars=true]),
				    #"Tipo Alterado" = Table.TransformColumnTypes(#"Cabeçalhos Promovidos",{{"REF_SMART", type text}, {"TIPO SMART", type text}, {"SMART?", type text}, {"Familia_SKU", type text}, {"Marca_SKU", type text},  {"Raiz", type any}, {"REFERENCIA", type text}, {"REF_SMART_1", type text}, {"TIPO SMART_2", type text}, {"SMART?_3", type text}, {"Familia_SKU_4", type text}, {"Marca_SKU_5", type text}, {"Mês", Int64.Type}, {"Mês_6", type text}})
				in
				    #"Tipo Alterado"

	changedProperty = IsHidden

	annotation PBI_NavigationStepName = Navegação

	annotation PBI_ResultType = Table

